version: '3'

services:
  fhir:
    container_name: fhir
    image: hapiproject/hapi:v5.3.0
    ports:
      - "3009:8080"
    environment:
      profiles.active: r4
      spring.datasource.url: 'jdbc:postgresql://db:5432/hapi'
      spring.datasource.username: admin
      spring.datasource.password: admin
      spring.datasource.driverClassName: org.postgresql.Driver
    depends_on:
      - db
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: hapi
    # not needed for networking between containers but here for troubleshooting
    ports:
      - "5439:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
  server:
    container_name: server
    build: .
    ports:
      - "3006:3006"
    volumes:
      - .:/app
    command: npm run dev